[workspace]

members = [
    "libs/any_result",
    "libs/gl_obj",
    "libs/gl_safe",
    "libs/matrix",
    "libs/vector",
    "libs/wavefrontobj",
    "libs/imageutil",
    "libs/raytrace",

    "scathanna_core",
    "scathanna_server",
    "scathanna",
]

exclude = [
    "obj2map",
]