[package]
name = "scathanna_server"
version = "1.0.0"
authors = ["Arne Vansteenkiste <barnex@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
scathanna_core = {path = "../scathanna_core"}
structopt = "0.3"
fnv = "1"

[profile.release]
lto = true